name: Lint
on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Terraform format
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: 1.3.3
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "."
          tf_actions_comment: false

      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.42.2

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
